---
title: "01-Techme包设计"
---

## 数据集安全性：暂时不对外开放

本项目目前托管在github上，目前项目仓库设置为**private**，不对外开放。

考虑到原始数据可能包含从多个渠道抓取到的敏感数据，因此本数据集暂时不对外开放。

本数据集的开发和构建，仅限于内部使用，完全服务于“中国旱区农业科技发展报告”的年度报告编写工作。

## 数据管理的理念：兼顾效率和可扩展性

**实际需求导向**。数据的新增变更应坚持“如无必要，不增实体”的功利性原则，以保证数据集维护效率。

**可扩展和更新**。因为数据来源各不相同，随时间推移，新的指标和数据会不断加入。要求能够快速扩展和准确更新。更新和维护工作一般是根据研究任务而定，基本上是按年度进行。其中，需要比较繁重的手工录入和校正工作，自动化编码可以使用的场景比较有限，因为数据来源和口径都比较混乱。

**独立性和全局性**。撰写研究报告时，具体内容仅涉及到特定**数据子集**，基于内容的数据子集使用率最高，因此需要保持这部分子集的独立性，以方便随时审查和调用。全局性的**超大数据集**，并不是一个重要的目的，一般使用率比较低，更应该把它视作是自发维护后的一个结果（副产物）。


## 数据集来源构成：年鉴数据和公开网络数据

目前数据集主要有两个来源：

- 年鉴数据：包括中国农村统计年鉴、中国科技统计年鉴、中国统计年鉴等。从中国知网的中国社会经济统计数据库（西农权限）获取xls文件（文档经过加密），然后通过本项目的workflow内部函数处理为统一的xlsx文件。

- 公开网络数据：包括中国农业农村部、中国科技部、中国教育部等官方网站发布的数据。一般需要通过网络爬虫技术来获取。

## 文件夹系统与处理流程：初始资料到清洗资料

经过清洗整理后的数据，全部会存放在`data-raw/data-tidy`文件夹中。然后再使用`usethis::use_data()`函数来构建和发布标准数据集。

但是，在数据清洗和整理的过程中，需要根据数据集的来源和处理流程，来决定数据存放的文件夹。

1. 对于年鉴数据集，需要把原始资料和清洗后的数据分别存放在不同的文件夹中：

- 原始资料存放在`data-raw/xxx-yearbook/`文件夹中。
- 清洗后的数据存放在`data-raw/data-tidy/xxx-yearbook/`文件夹中。


2. 对于网络数据集，可以放在同一个文件夹中：

- 原始资料存放在`data-raw/data-tidy/xxx-web/html/`文件夹中。
- 清洗后的数据存放在`data-raw/data-tidy/xxx-web/xlsx/`文件夹中。

## 变量定义系统：统一编码和可扩展

**变量定义系统**：标准数据集中，唯一需要设定的是变量命名。要求做到：（1）唯一性，变量增多后命名的唯一性可能会受到挑战；（2）定位性，变量命名能反映数据集空间维度的坐标特征，如哪个区、什么节点、何种值；（3）可读性，变量命名能较快速地揭示变量的实际经济意义；（4）易用性，变量名不能太长，避免引用过于复杂。

 **区块命名法**：根据数据空间维度关系，按**“区-部-节-点”**的原则设置4个区块段，保证变量命名的唯一性。
 
- `block1`：以v0x表达，代表最高分区。如v04表示**科技**。
- `block2`：代表所属区下面的某个分部，如v04_gx表示**科技**分区下的**高校**分部。
- `block3`：代表所属分部下面的某个小节，如v04_gx_nbzc表示**科技**分区下的**高校**分部的**内部支出**。
- `block4`：代表所属小节下面的某个具体点值，为最末一级。如v04_gx_nbzh_jcyj表示**科技**分区下、**高校**分部、**内部支出**、**基础研究**。

**变量版本迭代（version）**：根据对四个必备特征的权衡，变量定义系统可能会发生改变，因此需要标识不同的变量版本。如`v2019.8`表示某次调整后的变量定义体系。应附注记录改变的主要依据：如“保持与年鉴表达的一致性”

- 如果要新增变量命名，直接按最新版本规则来定义，新增即可。（按新的命名规则，并记录版本号）
- 如果要调整变量命名，不要删除旧的变量命名，直接在其后新增一条记录即可。（按新的命名规则，并记录版本号）

**附属信息**：变量取值在数据更新时也可能面临统计口径和单位的变化。此外，必要的中文信息也是很重要。因此需要添加必要的**附属信息**。

- 单位（unit）：变量取值的单位。
- block1-block4对应中文含义：

**自动生成变量名**：根据**“区-部-节-点”**的原则直接来生成变量名，基本能保证以上的四个基本命名要求。

- 自动生成变量名：如v04_gx_nbzh_jcyj
- 自动生成摘要标签： 如“高校_内部支出_基础研究”

